In [1]:
import numpy as np

In [4]:

import numpy as np
arr1= np.arange (100,200)
arr1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [5]:
print (arr1[10:],'\n')

[110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199] 



In [6]:
print (arr1[:20],'\n')

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119] 



In [7]:

print (arr1[10:20],'\n')

[110 111 112 113 114 115 116 117 118 119] 



In [8]:
print (arr1[10:50:5])

[110 115 120 125 130 135 140 145]


In [9]:


print (arr1[::10])


[100 110 120 130 140 150 160 170 180 190]


In [10]:


print (arr1[::-10])

[199 189 179 169 159 149 139 129 119 109]


In [11]:
arr_slice = slice (1,10,2)
print (arr_slice)
print (arr1[arr_slice])


slice(1, 10, 2)
[101 103 105 107 109]


In [12]:
arr1 =  np.arange(9)
print (arr1)
arr1=arr1.reshape(3,3)
arr1

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr1[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [16]:
arr1[1:,1:]

array([[4, 5],
       [7, 8]])

In [17]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
arr2 = arr1[:2]
print (arr2)


[[0 1 2]
 [3 4 5]]


In [21]:
arr2 = arr1[:2,0:2]
print (arr2)

[[0 1]
 [3 4]]


In [22]:
print (arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
print (arr1.shape)

(3, 3)


In [24]:
print (arr1.ndim)

2


In [25]:
print (arr1.itemsize)

4


In [26]:
print (arr1.dtype)

int32


In [27]:
print (arr1.size)

9


In [28]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
print (arr1.min())

0


In [30]:

print (arr1.max())

8


In [32]:

print (arr1.sum())

36


In [33]:

print (np.sqrt(arr1))



[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [34]:
print (np.std(arr1))

2.581988897471611


In [35]:
arr5 = np.empty([3,2], dtype =  float)
print (arr5)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [36]:
arr5 = np.empty([3,2], dtype =  int)
print (arr5)


[[1568221584        504]
 [         0          0]
 [         1  757935405]]


In [37]:
arr5 = np.empty([3,2], dtype =  str)
print (arr5)


[['' '']
 ['' '']
 ['' '']]


In [38]:
arr5 = np.empty([3,2], dtype = bool)
print (arr5)

[[False False]
 [False False]
 [False False]]


In [39]:
dir (np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [40]:
import numpy 
for name in dir(numpy):
    print (name, end = '\t')   


ALLOW_THREADS	AxisError	BUFSIZE	CLIP	ComplexWarning	DataSource	ERR_CALL	ERR_DEFAULT	ERR_IGNORE	ERR_LOG	ERR_PRINT	ERR_RAISE	ERR_WARN	FLOATING_POINT_SUPPORT	FPE_DIVIDEBYZERO	FPE_INVALID	FPE_OVERFLOW	FPE_UNDERFLOW	False_	Inf	Infinity	MAXDIMS	MAY_SHARE_BOUNDS	MAY_SHARE_EXACT	ModuleDeprecationWarning	NAN	NINF	NZERO	NaN	PINF	PZERO	RAISE	RankWarning	SHIFT_DIVIDEBYZERO	SHIFT_INVALID	SHIFT_OVERFLOW	SHIFT_UNDERFLOW	ScalarType	Tester	TooHardError	True_	UFUNC_BUFSIZE_DEFAULT	UFUNC_PYVALS_NAME	VisibleDeprecationWarning	WRAP	_CopyMode	_NoValue	_UFUNC_API	__NUMPY_SETUP__	__all__	__builtins__	__cached__	__config__	__deprecated_attrs__	__dir__	__doc__	__expired_functions__	__file__	__getattr__	__git_version__	__loader__	__name__	__package__	__path__	__spec__	__version__	_add_newdoc_ufunc	_distributor_init	_financial_names	_from_dlpack	_globals	_mat	_pytesttester	_version	abs	absolute	add	add_docstring	add_newdoc	add_newdoc_ufunc	alen	all	allclose	alltrue	amax	amin	angle	any	append	apply_along_axis	appl

In [41]:
arr = np.array([1, 2, 3, 4, 5]) 
print (arr)
print (arr.dtype)
print ('\n')
float_arr = arr.astype(np.float64) 
print (float_arr)
print (float_arr.dtype)


[1 2 3 4 5]
int32


[1. 2. 3. 4. 5.]
float64


In [42]:
float_arr = arr.astype(np.bool) 
print (float_arr)
print (float_arr.dtype)

[ True  True  True  True  True]
bool


C:\Users\noble\AppData\Local\Temp\ipykernel_11412\1342837148.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  float_arr = arr.astype(np.bool)


In [43]:
np.array(['1.25','-9.6','42'], dtype=np.string_)

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [44]:
np.array([1.25,-9.6,42], dtype=np.int)

C:\Users\noble\AppData\Local\Temp\ipykernel_11412\160474310.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1.25,-9.6,42], dtype=np.int)


array([ 1, -9, 42])

In [45]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


In [46]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [47]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr)[::-1])


['cherry' 'banana' 'apple']


In [48]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [50]:

arr = np.array([[3, 2, 4], [5, 0, 1]])
print (arr)
print ()
print (np.sort(arr, axis = 0))


[[3 2 4]
 [5 0 1]]

[[3 0 1]
 [5 2 4]]


In [52]:
arr = np.array([[3, 2, 4],
                [5, 0, 1]])
arr

array([[3, 2, 4],
       [5, 0, 1]])

In [53]:
arr = -np.sort(-arr)
print(arr)


[[4 3 2]
 [5 1 0]]
